"""Corpus freshness.

The store is derived from `problems/` and nothing re-derives it automatically.
A store built 45 minutes before the migration code was finalised carried two
retired problems through a whole session — vectors, an all-pairs sweep, and a
set of reported thresholds, all resting on records the corpus had dropped. The
numbers survived it; one reported dedup candidate did not. These tests are the
thing that was missing, not the fix for that particular drift.
"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

import os
import sqlite3

import pytest

from migrate.from_corpus import corpus_fingerprint, corpus_files
from store import db

CORPUS = pathlib.Path(__file__).resolve().parents[2] / "problems"
needs_corpus = pytest.mark.skipif(not CORPUS.is_dir(), reason="corpus absent")


@pytest.fixture
def corpus(tmp_path):
    (tmp_path / "tier-failure-history").mkdir()
    (tmp_path / "actors").mkdir()
    (tmp_path / "data-model.yaml").write_text("a: 1\n")
    (tmp_path / "actors" / "x.md").write_text("---\nname: X\n---\n\n# X\n")
    return tmp_path


def test_fingerprint_is_stable_across_runs(corpus):
    assert corpus_fingerprint(corpus) == corpus_fingerprint(corpus)


def test_fingerprint_ignores_mtime(corpus):
    """Content hashes, not mtimes — a checkout or a `touch` moves every mtime
    in the tree without changing a byte, and would otherwise cry wolf."""
    before = corpus_fingerprint(corpus)
    os.utime(corpus / "actors" / "x.md", (0, 0))
    assert corpus_fingerprint(corpus) == before


def test_fingerprint_moves_when_a_byte_does(corpus):
    before = corpus_fingerprint(corpus)
    (corpus / "actors" / "x.md").write_text("---\nname: Y\n---\n\n# Y\n")
    assert corpus_fingerprint(corpus) != before


def test_fingerprint_moves_when_a_record_is_added_or_removed(corpus):
    before = corpus_fingerprint(corpus)
    added = corpus / "actors" / "y.md"
    added.write_text("---\nname: Y\n---\n")
    assert corpus_fingerprint(corpus) != before
    added.unlink()
    assert corpus_fingerprint(corpus) == before


def test_fingerprint_covers_a_rename(corpus):
    """Path is hashed alongside content, so moving a record without editing it
    still counts as a change — an id lives in its filename."""
    before = corpus_fingerprint(corpus)
    (corpus / "actors" / "x.md").rename(corpus / "actors" / "renamed.md")
    assert corpus_fingerprint(corpus) != before


def test_an_unstamped_store_is_reported_not_trusted(corpus):
    """The store that actually drifted had no stamp at all, so silence on a
    missing stamp would have passed the exact case this exists for."""
    conn = db.connect(":memory:")
    assert db.stamped(conn) is None
    assert "predates the freshness check" in db.check_fresh(conn, "abc")


def test_a_stamped_store_matches_only_its_own_corpus(corpus):
    conn = db.connect(":memory:")
    db.stamp(conn, corpus_fingerprint(corpus))
    assert db.check_fresh(conn, corpus_fingerprint(corpus)) is None
    (corpus / "actors" / "x.md").write_text("changed\n")
    message = db.check_fresh(conn, corpus_fingerprint(corpus))
    assert message and "re-run" in message


def test_require_fresh_stops_by_default_and_warns_when_told_not_to(corpus):
    from embed.guard import require_fresh
    conn = db.connect(":memory:")
    db.stamp(conn, "not-this-corpus")
    with pytest.raises(SystemExit) as caught:
        require_fresh(conn, corpus)
    assert "from_corpus" in str(caught.value)

    said = []
    assert require_fresh(conn, corpus, allow=True, log=said.append) is not None
    assert any("--stale-ok" in line for line in said)


def test_a_missing_corpus_is_a_refusal_not_a_pass(tmp_path):
    from embed.guard import require_fresh
    conn = db.connect(":memory:")
    with pytest.raises(SystemExit):
        require_fresh(conn, tmp_path / "nope")


@needs_corpus
def test_the_migration_stamps_what_it_read(tmp_path):
    from migrate.from_corpus import run
    out = tmp_path / "g.db"
    run(CORPUS, out)
    conn = sqlite3.connect(out)
    conn.row_factory = sqlite3.Row
    assert db.stamped(conn) == corpus_fingerprint(CORPUS)
    assert db.check_fresh(conn, corpus_fingerprint(CORPUS)) is None


@needs_corpus
def test_the_fingerprint_covers_exactly_what_the_migration_reads(tmp_path):
    """Both directions, and both are real failures.

    Too narrow and the fingerprint lies by omission — a record source it misses
    can change while the guard reports the store fresh. Too wide and the guard
    fires on files no record comes from: `follow-list.md` is regenerated by
    every `npm run build`, so a glob that swept it in meant a routine build made
    the store look stale, and a guard that cries wolf gets `--stale-ok`'d until
    it means nothing.

    Measured rather than asserted file-by-file: run a real migration with
    `Path.read_text` / `read_bytes` / `open` instrumented, and compare. The
    fingerprint's own reads are excluded — it reads every file it hashes, which
    would make the comparison pass by construction."""
    import migrate.from_corpus as fc

    seen: set[pathlib.Path] = set()
    real = (pathlib.Path.read_text, pathlib.Path.read_bytes, pathlib.Path.open)
    fingerprint = fc.corpus_fingerprint
    fc.corpus_fingerprint = lambda corpus: "stub"
    pathlib.Path.read_text = lambda s, *a, **k: (seen.add(s.resolve()), real[0](s, *a, **k))[1]
    pathlib.Path.read_bytes = lambda s, *a, **k: (seen.add(s.resolve()), real[1](s, *a, **k))[1]
    pathlib.Path.open = lambda s, *a, **k: (seen.add(s.resolve()), real[2](s, *a, **k))[1]
    try:
        fc.run(CORPUS, tmp_path / "g.db")
    finally:
        pathlib.Path.read_text, pathlib.Path.read_bytes, pathlib.Path.open = real
        fc.corpus_fingerprint = fingerprint

    root = CORPUS.resolve()
    read = {p for p in seen if str(p).startswith(str(root))}
    hashed = {p.resolve() for p in corpus_files(CORPUS)}
    rel = lambda ps: sorted(p.relative_to(root).as_posix() for p in ps)
    assert rel(hashed - read) == [], "fingerprinted but never read — false staleness"
    assert rel(read - hashed) == [], "read but not fingerprinted — the guard is blind to these"
    assert len(read) > 300, f"only {len(read)} files read; the migration did not run"


def test_both_embed_clis_share_one_set_of_store_flags():
    """The flags and the check are one thing: a tool that accepts `--stale-ok`
    and forgets to call the guard accepts the flag and ignores it. Defaults are
    absolute, so a bare run means the same store from `engine/` and from the
    repo root — the two had disagreed."""
    import argparse
    from embed.guard import REPO, add_store_args
    from embed import backfill, calibrate

    for module in (backfill, calibrate):
        src = pathlib.Path(module.__file__).read_text()
        assert "add_store_args(ap)" in src and "open_store(args" in src, module.__name__

    args = add_store_args(argparse.ArgumentParser()).parse_args([])
    assert pathlib.Path(args.db) == REPO / "problems" / "graph.db"
    assert pathlib.Path(args.corpus) == REPO
    assert pathlib.Path(args.db).is_absolute()
