#!/usr/bin/env node
// Flat, scannable follow list -> problems/follow-list.md
// Unfollowed first, so the file is a worklist: open, follow, tick.
//   node scripts/follow-list.mjs [--ecosystem] [--tracked]
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { parse } from 'yaml';

const ROOT = new URL('..', import.meta.url).pathname;
const DIR = join(ROOT, 'problems/actors');
const args = process.argv.slice(2);
const only = { eco: args.includes('--ecosystem'), tracked: args.includes('--tracked') };

const RANK = ['x', 'substack', 'newsletter', 'linkedin', 'instagram', 'youtube',
  'rss', 'facebook', 'website', 'press', 'annual-report', 'filings', 'other'];

const rows = [];
for (const f of readdirSync(DIR).filter((f) => f.endsWith('.md') && !f.startsWith('_'))) {
  const raw = readFileSync(join(DIR, f), 'utf8');
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) continue;
  let a; try { a = parse(m[1]); } catch { continue; }
  if (!a?.slug) continue;
  if (a.depth === 'excluded') continue;              // deliberately out of the network
  if (only.tracked && a.depth !== 'tracked') continue;
  if (only.eco && !(a.ecosystem_role ?? []).length) continue;

  const live = (a.sources ?? []).filter((s) => s.url && s.status !== 'dead' && s.status !== 'none-found');
  live.sort((x, y) => RANK.indexOf(x.kind) - RANK.indexOf(y.kind));
  rows.push({
    name: a.name ?? a.slug, slug: a.slug, type: a.type,
    followed: a.followed === true,
    role: [...(a.ecosystem_role ?? []), ...(a.leg ?? [])].join('/') || '—',
    depth: a.depth ?? 'registry',
    feeds: live.slice(0, 2),
    none: live.length === 0,
  });
}

// individuals before orgs — you follow people, not letterheads
const order = (r) => [r.followed ? 1 : 0, r.none ? 1 : 0, r.type === 'individual' ? 0 : 1,
  r.depth === 'tracked' ? 0 : 1, r.name.toLowerCase()];
rows.sort((a, b) => { const x = order(a), y = order(b);
  for (let i = 0; i < x.length; i++) if (x[i] !== y[i]) return x[i] < y[i] ? -1 : 1; return 0; });

const line = (r) => {
  const feeds = r.feeds.map((s) => `[${s.kind}](${s.url})${s.handle ? ` \`${s.handle}\`` : ''}`).join(' · ')
    || '_no channel found_';
  return `- [${r.followed ? 'x' : ' '}] **${r.name}** · ${r.role} · ${feeds} · [record](actors/${r.slug}.md)`;
};

const todo = rows.filter((r) => !r.followed && !r.none);
const nofeed = rows.filter((r) => !r.followed && r.none);
const done = rows.filter((r) => r.followed);

const out = [
  '<!-- GENERATED by scripts/follow-list.mjs — edit the actor records, not this file.',
  '     Except the checkboxes: tick here, then set `followed: true` in the record. -->',
  '# Follow list', '',
  `_${rows.length} actors · ${todo.length} to follow · ${done.length} followed · ${nofeed.length} unreachable — regenerated ${new Date().toISOString().slice(0, 10)}_`,
  '', `## To follow (${todo.length})`, '', ...todo.map(line),
  '', `## Followed (${done.length})`, '', ...done.map(line),
  '', `## No reachable channel (${nofeed.length})`,
  '', '_Not a gap in the research — for many of these it is the finding._', '',
  ...nofeed.map((r) => `- **${r.name}** · ${r.role} · [record](actors/${r.slug}.md)`),
  '',
].join('\n');

writeFileSync(join(ROOT, 'problems/follow-list.md'), out);
console.log(`follow-list: ${rows.length} actors · ${todo.length} to follow · ${nofeed.length} unreachable`);
